Jl 7 big wig coverage
Lab-Jaiswal/workflows pull request #36
Opened 2022-01-14 20:53 UTC by maurermaggie

(1) Please note that the .bd files **have to** be sorted in order to be processed by the bedfiletoBigWig command
(2) I moved the genomeconv and bedfiletoBigWig commands to the sort.sh file (now named footprint_processing.sh) because it is faster and easier to keep all slurm steps together
(3) I renamed sort.sh to footprint_processing.sh because that file now contains a lot more than sorting commands
(4) I moved Step 2 (genome prep) to before Step 1 (footprint processing) because its analysis is not tied to conditions, while the other steps (merging, sorting, bedgraphtoBigWig, etc.) are tied to conditions.

Please let me know if you have any advice or questions!

2022-01-14 23:35 UTC, rodriguesk commented on ATACseq_footprinting/atacseq_footprinting_pipeline.sh
> +#####################################---STEP 1: CREATE COVERAGE BIGWIG TRACK---###################################################
Do you mean coverage BED file here? The output seems to be a bed files?

2022-01-14 23:36 UTC, rodriguesk commented on ATACseq_footprinting/atacseq_footprinting_pipeline.sh
> +    echo "coverage files for the BigWig track have already been created"
Are the BigWig track files bed files? I thought bigwig is a separate file format than bed files.

2022-01-14 23:48 UTC, rodriguesk requested changes
Your code could probably improve with a little more commenting in the footprint_processing.sh for what each section is doing (similar to the code sections in your other pipelines). This also helps me code review much easier too and ensure things are doing what you want them to do. 

I think it's smart to put all the footprint_processing stuff into the footprint_processing.sh
Technically though it's not footprint_processing. It's ATACseq processing. Footprinting comes after the processing is done. Changing the file name again to something like ATACseq_processing.sh or BAM_processing.sh would be clearer IMO.

2022-01-18 20:40 UTC, maurermaggie commented
Please see changes I made @rodriguesk

2022-01-18 23:23 UTC, merged